language: julia
os:
    - linux
julia:
    - 0.5

notifications:
    email: false

before_install:
    - julia -e 'Pkg.add("Blosc")'
    - julia -e 'Pkg.add("Requests")'
    - julia -e 'Pkg.clone("https://github.com/seung-lab/BOSSArrays.jl.git")'

script:
    - julia -e 'Pkg.test("BOSSArrays")'
